update Universal link
reformcollective/library pull request #66
Opened 2023-10-16 17:13 UTC by davidthecomposer

updated universal Link and page transition to handle scrollable links. Since we have to wait until after the page transition to  make sure all the pinning/triggers are ok I decided on updating the library component. It is completely optional to add the  scrollable link so shouldn't impact normal usage.

2023-10-16 17:23 UTC, RJWadley requested changes

2023-10-16 17:23 UTC, RJWadley commented on Loader/TransitionUtils.ts
> +    if (anchor) {
To make things simpler, I'd recommend not adding logic to this file & keeping it as part of UniversalLink.tsx

i don't see a benefit to having it as part of `loadpage` so it just adds complexity.

2023-10-16 17:23 UTC, RJWadley commented on Loader/UniversalLink.tsx
> +  anchor?: string
A smarter way to do this would be to check the `to` prop. if it starts with `#`, trigger a scrollTo. otherwise load page as normal

2023-10-16 17:23 UTC, RJWadley commented on Loader/UniversalLink.tsx
> +  anchor?: string
then we could treat anchors like normal links

2023-10-17 17:18 UTC, davidthecomposer commented on Loader/TransitionUtils.ts
> +    if (anchor) {
updated this. We moved it to a different place and I've changed this to include parsing the url for an anchor in the universal Link component instead.

2023-10-17 17:18 UTC, davidthecomposer commented on Loader/UniversalLink.tsx
> +  anchor?: string
updated to this.

2023-10-17 17:25 UTC, RJWadley approved these changes

2023-10-17 17:27 UTC, RJWadley commented on Loader/UniversalLink.tsx
> +  const isAnchor = to.includes("#")
probably more robust to do `(new URL(to)).hash` which would give you something like `#CTA`

2023-10-17 17:27 UTC, RJWadley commented on Loader/UniversalLink.tsx
> +  const isAnchor = to.includes("#")
that way you don't have to do any string logic yourself

2023-10-17 17:36 UTC, merged